version: '3'
services:
  sql-db-dev:
    image: mysql:8.0
    container_name: mysql-senda-turistica-dev
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_DATABASE=db_senda_turistica_dev
      - MYSQL_USER=rafael-dev
      - MYSQL_PASSWORD=cibertec
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
  sql-db-test:
    image: mysql:8.0
    container_name: mysql-senda-turistica-test
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_DATABASE=db_senda_turistica_test
      - MYSQL_USER=rafael-test
      - MYSQL_PASSWORD=cibertec
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3308:3306"